# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 정해원 (Jeong HaeWon)
title: 중앙대학교 AI학과 (2022.03-2026.02)
email: haewon0430@cau.ac.kr
website: https://github.com/haewon22

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/정해원.JPEG
about_content: | # this will include new lines to allow paragraphs
  중앙대학교 AI학과에 재학 중인 정해원입니다. 특히 컴퓨터 비전(Computer Vision)과 비전-언어 모델(Vision-Language Models)에 깊은 관심을 가지고 있으며, 관련 연구실에서 인턴십을 통해 실제 연구에 참여하고 싶습니다.
  My name is haewon Jeong, an undergraduate student majoring in Artificial intelligence at Chung-Ang University.    
  I'm especialy interested in Computer Vision and Vision-Language Models.


content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Disentangling Classes in CLIP for Fine-Grained Tasks
  #       link: https://github.com/haewon22/UnmixClip_.git
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UnmixCLIP 구현
        link: https://github.com/haewon22/UnmixClip_.git
        # link_text: boringcompany.com
        sub_title: CLIP 모델의 Fine-Grained Task를 위한 클래스 분리(Disentangling Classes in CLIP for Fine-Grained Tasks)
        caption: 2025.03.17-2025.06.23
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            본 프로젝트에서는 Fine-Grained Task에서 CLIP 모델의 성능 향상을 목표로, 클래스 간의 혼란을 줄이기 위한 UnmixCLIP 논문을 재구현하였습니다. PyTorch를 활용하여 모델을 구현하고, PASCAL VOC 데이터셋에 적용하여 성능을 검증했습니다. 이 프로젝트를 통해 딥러닝 모델 구현 능력과 논문 분석 능력을 향상시킬 수 있었습니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 중앙대학교(Chung-Ang University)
        caption: 2022 - 2026
        link: https://www.cau.ac.kr/
        sub_title: AI학과 (Department of Artificial Intelligence)
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          중앙대학교 AI학과에서 딥러닝, 컴퓨터 비전, 자연어 처리, 음성처리 등 인공지능 분야의 핵심 과목들을 수강하며 탄탄한 기초 지식을 쌓았습니다.

  - title: A Little More About Me
    layout: text
    content: |
      저는 새로운 기술을 배우고 적용하는 것에 흥미를 느끼며, 팀 프로젝트에서 협업하는 것을 중요하게 생각합니다. 연구실 인턴십을 통해 실제 연구 환경에서 문제 해결 능력을 키우고, 다양한 연구자들과 교류하며 성장하고 싶습니다.

      개인적인 관심사로는:
      - (본인의 취미나 관심사)
      - (본인의 취미나 관심사)
      - [How to be Ninja 2.0](https://www.youtube.com/watch?v=yYy7gD2cK4o)
          Look at this cool image  
          ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
